### ISSUE TITLE
Create a Webpage for spotify Playlist

### ISSUE THREAD

**Issue by Vedant003** [Vedant003/webpage-for-porfolio#3]
Create a clean webpage with good CSS for streaming a spotify playlist. Atleast 10 any playlist is needed to be added. You can choose any UI-UX for it, CSS is need to be in focused. For playlist links you can also comment me.

**Comment by manojku1803** [comment]
Hey, can you assign to me.

**Comment by Vedant003** [comment]
sure @manojku1803 ,good luck

**Comment by manojku1803** [comment]
Please specify that in a playlist 10 songs are added or 10 playlist are add.

**Comment by Vedant003** [comment]
> Please specify that in a playlist 10 songs are added or 10 playlist are add.

10 playlist is need to be added , you can take any randam or yours playlist

**Comment by manojku1803** [comment]
In one playlist atleast how many songs added

**Comment by Vedant003** [comment]
> In one playlist atleast how many songs added

use playlist from my profile https://open.spotify.com/user/31icqmepl4tmn44eoixufqg3cvem?si=f3ec9f0c85f24f64

**Comment by manojku1803** [comment]
check this changes are good or not

**Comment by Vedant003** [comment]
css looks perfect, but playlist was needed to be added from the spotify embid links also found an issues in header socails icons which are shifted towards left, rest all good

**Comment by manojku1803** [comment]
Now check this changes

**Comment by Vedant003** [comment]
Great @manojku1803 ,Thank You it looks perfect now
